custom_components/solvis_control/const.py
custom_components/solvis_control/translations/de.json
custom_components/solvis_control/translations/en.json

Hinzufügen von Features für die Wärmepumpe

---

README.md
supported-entites.md

This PR adds a list of all currently known modbus entites and their current support state.

[FEATURE] Add documentation for entites

---

custom_components/solvis_control/const.py
custom_components/solvis_control/coordinator.py
custom_components/solvis_control/manifest.json
custom_components/solvis_control/number.py
custom_components/solvis_control/select.py
custom_components/solvis_control/sensor.py
custom_components/solvis_control/switch.py

Fixes & Version string parsing

---

custom_components/solvis_control/config_flow.py
custom_components/solvis_control/number.py
custom_components/solvis_control/select.py
custom_components/solvis_control/sensor.py
custom_components/solvis_control/switch.py

Check entered connection details during ConfigFlow and OptionsFlow and added SW and HW version to DeviceInfo

[FEATURE]: Added check for valid modbus configuration and added Software and Hardware version to DeviceInfo

---

README.md

docs-high-level-description - The documentation includes a high-level description of the integration brand, product, or service
docs-installation-instructions - The documentation provides step-by-step installation instructions for the integration, including, if needed, prerequisites

small doc changes in readme

---

custom_components/solvis_control/const.py
custom_components/solvis_control/coordinator.py

add word_order to ModbusFieldConfig
add read-conversion for little-endian
Fixes https://github.com/LarsK1/hass_solvis_control/issues/96

minor changes due to https://github.com/LarsK1/hass_solvis_control/issues/96

---

custom_components/solvis_control/const.py
custom_components/solvis_control/strings.json
custom_components/solvis_control/translations/de.json
supported-entities.md

Fixes https://github.com/LarsK1/hass_solvis_control/issues/144

Feat: Add Analog Out Ox

---

custom_components/solvis_control/const.py
custom_components/solvis_control/number.py
custom_components/solvis_control/select.py
custom_components/solvis_control/sensor.py

Fixes https://github.com/LarsK1/hass_solvis_control/issues/148

Feat: Store raw or unprocessed values in entities extra attributes

---

README.md
custom_components/solvis_control/const.py
custom_components/solvis_control/icons.json
custom_components/solvis_control/translations/de.json

- changed hkr1_room_temp to input_type numer and edit=True ind const.py
- added corresponding entries in icons.json and de.json
- fixed manual installation instructions in readme.md
fix: #10

Fix: hkr1_room_temperature write feature

---

custom_components/solvis_control/const.py
custom_components/solvis_control/icons.json
custom_components/solvis_control/translations/de.json

change heat_generator_sx_power_current to pv2heat_energy #54 see also #173
fix #54

Feat: Add PV2Heat energy

---

custom_components/solvis_control/const.py
custom_components/solvis_control/icons.json
custom_components/solvis_control/translations/de.json
supported-entities.md

Feat: add pv2heat_power_electric (reg. 33548)

---

custom_components/solvis_control/translations/de.json

Feat: Naming completely revised and standardized

---

custom_components/solvis_control/config_flow.py
custom_components/solvis_control/manifest.json
custom_components/solvis_control/translations/de.json

fixed version in manifest.json to 2.0.0-alpha.11

feat: extend and improve config flow texts

---

custom_components/solvis_control/select.py
custom_components/solvis_control/utils/helpers.py
pytest.ini
tests/test_select.py

fix misc problems in select.py

feat: increase test coverage of test.py to 91%

---

custom_components/solvis_control/binary_sensor.py
custom_components/solvis_control/config_flow.py
custom_components/solvis_control/select.py
custom_components/solvis_control/utils/helpers.py
pytest.ini
tests/conftest.py
tests/test_config_flow.py
tests/test_select.py

completely revised test_config_flow
fixed many bugs discovered by tests

feat: increase overall test coverage to 57%

---

custom_components/solvis_control/const.py
custom_components/solvis_control/coordinator.py
custom_components/solvis_control/icons.json
custom_components/solvis_control/number.py
custom_components/solvis_control/translations/de.json

solves a bug in implementation of https://github.com/LarsK1/hass_solvis_control/issues/172
fixes general bugs as well

fix: hkrx_room_temp can not be set via ui

---

README.md
polling-groups.md

add new polling-groups.md since supported-entities.md is quite big already
partly solves #171

feat: add polling groups list

---

custom_components/solvis_control/config_flow.py
tests/test_config_flow.py

Increase total test coverage to 60%.
Progress towards #158.

feat: increase config_flow test coverage to 74%

---

custom_components/solvis_control/config_flow.py
custom_components/solvis_control/coordinator.py
custom_components/solvis_control/utils/helpers.py
tests/conftest.py
tests/test_config_flow.py

fix: rebuild testing base structure

---

custom_components/solvis_control/config_flow.py
custom_components/solvis_control/utils/helpers.py
tests/conftest.py
tests/test_config_flow.py

Refine test infrastructure concerning modbus-mocks Increase total test converage to 71%
Progress towards #158

feat: increase config_flow test coverage to 93%

---

custom_components/solvis_control/number.py
custom_components/solvis_control/sensor.py
custom_components/solvis_control/switch.py
custom_components/solvis_control/utils/helpers.py

- Add new helper methods: process_coordinator_data and should_skip_register in helpers.py
- Update number.py, sensor.py, and switch.py to use new helper methods
- Fix bug causing incorrect registration of hkr1_room_temp
- Fix some smaller bugs
Progress on #159

Refactor: Clean up code and update helper methods

---

custom_components/solvis_control/binary_sensor.py

Refactor: Integrate helper methods in binary_sensor.py

---

custom_components/solvis_control/select.py
tests/conftest.py
tests/test_select.py

Move generic fixtures from test_select.py to conftest.py
Progress on #159

Refactor: select.py including test_select.py

---

custom_components/solvis_control/sensor.py
tests/test_binary_sensor.py
tests/test_number.py
tests/test_sensor.py
tests/test_switch.py

Create test_binary_sensor.py with coverage 100%
Create test_number.py with coverage 100%
Create test_sensor.py with coverage 100%
Create test_switch.py with coverage 100%
Remove small logic issue in sensor.py

Feat: increase overall test coverage to 84%

---

custom_components/solvis_control/config_flow.py
tests/test_config_flow.py

Feat: increase config_flow test coverage to 98%

---

custom_components/solvis_control/config_flow.py
custom_components/solvis_control/utils/helpers.py
tests/test_config_flow.py

Adjust exception handling in fetch_modbus_value (helpers.py) to propagate errors
Update corresponding error handling in config_flow.py

Feat: Increase test coverage for config_flow.py to 100%

---

custom_components/solvis_control/__init__.py
tests/test_init.py

Increase total coverage to 92%

Feat: add test_init with coverage 100%

---

custom_components/solvis_control/diagnostics.py

Update scan_modbus_registers to filter registers based on the REGISTERS constant in const.py
Fix #238

Refactor(diagnostics): scan only registers defined in REGISTERS

---

tests/test_diagnostics.py

Increase total test coverage to 95%

Feat: add test_diagnostics.py with coverage 100%

---

custom_components/solvis_control/coordinator.py
custom_components/solvis_control/utils/helpers.py
tests/conftest.py
tests/test_coordinator.py
tests/test_select.py

Refactor coordinator.py
Increase total test coverage to 97%
Progress on #158 and #159

Feat: add test_coordinator.py with coverage 100%

---

custom_components/solvis_control/utils/helpers.py
tests/test_helpers.py

Increase total test coverage to 100%
Solve #158

Feat: add test_helpers.py with coverage 100%

---

tests/conftest.py
tests/dummies.py
tests/test_coordinator.py
tests/test_helpers.py

refactor: test_coordinator & test_helpers

---

custom_components/solvis_control/const.py
custom_components/solvis_control/icons.json
custom_components/solvis_control/translations/de.json

Fix wrong register for hkr3_flow_water_temp_s14 (33039 > 33037)

Feat(Sensors): add temperatur sensor s16 (input-register 33039)

---

custom_components/solvis_control/binary_sensor.py
custom_components/solvis_control/entity.py
custom_components/solvis_control/number.py
custom_components/solvis_control/select.py
custom_components/solvis_control/sensor.py
custom_components/solvis_control/switch.py
custom_components/solvis_control/utils/helpers.py
tests/conftest.py
tests/test_binary_sensor.py
tests/test_entity.py
tests/test_helpers.py
tests/test_number.py
tests/test_select.py
tests/test_sensor.py
tests/test_switch.py

Add SolvisEntity as base entity for all sensor entities @ entity.py
Add async_setup_solvis_entities for all sensor entities @ helpers.py 
Add test_entity.py
Refactor test_select.py
Fix #159

Feat: refactor all sensor modules

---

.github/workflows/tests.yml
custom_components/solvis_control/__init__.py
custom_components/solvis_control/config_flow.py
custom_components/solvis_control/const.py
custom_components/solvis_control/coordinator.py
custom_components/solvis_control/translations/de.json
custom_components/solvis_control/utils/helpers.py
tests/test_config_flow.py
tests/test_init.py

Fix failing options_update_listener @ __init__.py
Fix #232

Feat: Add new config step for hkrx room temp sensors

---

README.md

DOC: Added SC2 screens and notes to readme

---

.github/workflows/tests.yml
supported-entities.md
tests/test_init.py

Docs: add issue references in supported_entities.md

---

custom_components/solvis_control/__init__.py
custom_components/solvis_control/binary_sensor.py
custom_components/solvis_control/config_flow.py
custom_components/solvis_control/const.py
custom_components/solvis_control/entity.py
custom_components/solvis_control/number.py
custom_components/solvis_control/select.py
custom_components/solvis_control/sensor.py
custom_components/solvis_control/switch.py
custom_components/solvis_control/translations/de.json
custom_components/solvis_control/utils/helpers.py
tests/test_config_flow.py
tests/test_entity.py
tests/test_init.py
tests/test_number.py
tests/test_switch.py

Feat: add config option for custom hkr* naming

---

.github/workflows/tests.yml
custom_components/solvis_control/const.py
custom_components/solvis_control/translations/de.json
custom_components/solvis_control/update.py
tests/test_update.py

fix: Migrate version sensors to Update platform
